import Head from 'next/head'
import { Container, Content } from '../styles/home';
import Header from "../components/Header";

export default function Home() {
  return (
    <Container>
        <Head>
            <title>Aplicadora Zona Sul</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/favicon.ico" />
        </Head>
        <Header />
        <Content>
            <h1>Aplicadora Zona Sul</h1>
        </Content>
    </Container>
  )
}
